title:              TAEHOON
email:              your-email@example.com
description:        어서오세요
author:             Start Bootstrap
baseurl:            ""
url:                "https://taehoonoh.github.io"


# Social Profiles
twitter_username:   SBootstrap
github_username:    taehoonoh
facebook_username:  StartBootstrap
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Disqus 

discus-identifier: taehoonoh-github # add your discus identifier



# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
